- api/config/index.js
- api/controllers/amritkeertan.js
- api/controllers/getJSON.js
- api/routes/index.js
- package.json
for https://github.com/KhalisFoundation/sttm-web/issues/24
> Add amrit keertan

- api/controllers/shabads.js
this changes the default searchtype
> Fix first letter start

- api/controllers/getJSON.js
- api/controllers/shabads.js
- package.json
Can add &livesearch=1 to the api call to have smaller db call and smaller json return
> Add live search

- api/controllers/shabads.js
> ignore spaces for first letter searches by removing them

- api/controllers/shabads.js
> Adds a way to check if it's latest hukamnama in API response

- api/controllers/shabads.js
- api/lib/index.js
> Adds ability to have multiple shabadIDs in the query

- api/controllers/shabads.js
- api/lib/getJSON.js
this was really complicated and im not confident enough in js to know if I did this right. but it works.
> Hukam multi shabad regression

- api/controllers/shabads.js
> always show next/prev when available

- api/controllers/shabads.js
use multiview only for hukamnama
> add option to always show multiview for shabads

- api/controllers/amritkeertan.js
- api/controllers/banis.js
- api/controllers/rehats.js
- api/controllers/shabads.js
- api/lib/index.js
> refactor errors to use a standard library and http err codes

- api/controllers/healthcheck.js
- api/routes/index.js
- package-lock.json
> Add health check

- api/controllers/shabads.js
- package-lock.json
- package.json
> use anvaad to convert unicode in gurmukhi searches to ascii

- api/controllers/rehats.js
- api/controllers/shabads.js
- package-lock.json
- package.json
fixes #42
depends on banidb/11 for banidb client 1.0.2
> adds first letter search for romanized english

- api/controllers/amritkeertan.js
- api/controllers/banis.js
- api/controllers/healthcheck.js
- api/controllers/rehats.js
- api/controllers/shabads.js
- app.js
- package.json
* Refactor mariadb connection pooling
* ensure req var is available to all  methods
> Refactor pooling (#139)

- api/controllers/shabads.js
- api/lib/searchOperators.js
Just creating a draft PR to keep track of progress.
Other operators for other searchTypes coming soon 👍
> Add new search operators

- api/lib/getJSON.js
- package.json
> fix lodash bug

- api/controllers/kosh.js
- api/lib/getJSON.js
- api/routes/index.js
- package.json
- Kosh 
- Punjabi Translation fix
> 2.6.0 Release

- api/controllers/metadata.js
- api/routes/index.js
- package.json
> Add metadata routes for writer, raag, source

- api/controllers/shabads.js
- package.json
- tests/e2e/__tests__/angs.tests.js
- tests/e2e/__tests__/search.tests.js
- tests/e2e/__tests__/shabads.tests.js
- tests/e2e/config.js
- Add test for dasam granth angs
- Remote tests for raag pages
- Add local test
- Update version string
> P0: Fix issue with ang sourceid

- api/controllers/shabads.js
- package.json
- tests/e2e/__tests__/angs.tests.js
- tests/e2e/__tests__/search.tests.js
- tests/e2e/__tests__/shabads.tests.js
- tests/e2e/config.js
- Add test for dasam granth angs
- Remote tests for raag pages
- Add local test
- Update version string
> P0: Fix issue with ang sourceid (#213)

- app.js
- package-lock.json
- package.json
- swagger.json
> Add swagger and api-docs endpoint

- api/controllers/shabads.js
- swagger.json
> Fix random endpoint when source is all. 

- .gitignore
- README.md
- api/controllers/shabads.js
- app.js
- bin/clean-up-docker-containers.sh
- bin/stop-docker.sh
- package-lock.json
- package.json
- swagger.json
- Adds API docs.
- Updates Anvaad dependency
> Release 2.8.4

- api/graphql/__generated__/schema-defs.js
- api/graphql/schema-types-defs/Verse.graphql
- api/lib/getJSON.js
Hindi translations are returned in the translation prop with key `hi`.
`hi` has 2 options `ss` (arth by sahib singh) and `sts` (arth by sant singh).
> Add hindi translations

- api/controllers/shabads.js
- api/lib/getJSON.js
Check other verses for writer info.
> Improve getWriter for shabads without writer in first verse. 

- api/controllers/shabads.js
- api/lib/getJSON.js
- package.json
> Release 2.9.1

- api/lib/searchOperators.js
https://stackoverflow.com/questions/61127906/mysql-like-with-json-extract
> Make english search case insensitivity

- api/lib/searchOperators.js
- package-lock.json
- package.json
- Case insensitivity for english search
> Release 2.9.2

- api/config/index.js
- app.js
- package-lock.json
- package.json
Added ability to use cluster pools or not (checks if DB_NODES array exists)
Also added ability to optionally use SSL_CA cert for connection
> Added ability to use cluster pools or not

- package-lock.json
- package.json
Updates the api version to 2.10.1 for a patch release.
> Minor version update: 2.10.1

- api/controllers/shabads.js
- package-lock.json
- package.json
Currently, the verses were sorted by their verse Id, we want it to be in the same order as sent in request. 
Also, fixes issue #271
> Sort verses in same order as given input

- package-lock.json
- package.json
> Release 2.10.3 - dev
